INSERT INTO images (nom, date, orientation, fichier, id_auteur, likes) VALUES ('lost', '2022-12-25', 1, 'image1', 1, 0);
INSERT INTO images (nom, date, orientation, fichier, id_auteur, likes) VALUES ('return', '2022-12-25', 1, 'image2', 1, 0);
INSERT INTO images (nom, date, orientation, fichier, id_auteur, likes) VALUES ('feels like summer - pt.1', '2022-12-25', 1, 'image3', 1, 0);
INSERT INTO images (nom, date, orientation, fichier, id_auteur, likes) VALUES ('feels like summer - pt.2', '2022-12-25', 1, 'image4', 1, 0);
INSERT INTO images (nom, date, orientation, fichier, id_auteur, likes) VALUES ('feels like summer - final', '2023-12-25', 1, 'image5', 1, 0);
INSERT INTO images (nom, date, orientation, fichier, id_auteur, likes) VALUES ('slow day', '2022-12-17', 1, 'image6', 1, 0);
INSERT INTO images (nom, date, orientation, fichier, id_auteur, likes) VALUES ('silent hills', '2023-12-17', 1, 'image7', 1, 0);
INSERT INTO images (nom, date, orientation, fichier, id_auteur, likes) VALUES ('running out of time?', '2022-12-25', 1, 'image8', 1, 0);
INSERT INTO images (nom, date, orientation, fichier, id_auteur, likes) VALUES ('running out of time?', '2022-12-25', 1, 'image9', 1, 0);
INSERT INTO images (nom, date, orientation, fichier, id_auteur, likes) VALUES ('sleepless nights - intro', '2023-01-02', 1, 'image10', 1, 0);
INSERT INTO images (nom, date, orientation, fichier, id_auteur, likes) VALUES ('sleepless nights - prelude', '2023-01-02', 1, 'image11', 1, 0);
INSERT INTO images (nom, date, orientation, fichier, id_auteur, likes) VALUES ('sleepless nights - prelude 2', '2023-01-02', 1, 'image12', 1, 0);
INSERT INTO images (nom, date, orientation, fichier, id_auteur, likes) VALUES ('sleepless nights - outro', '2023-01-02', 1, 'image13', 1, 0);
INSERT INTO images (nom, date, orientation, fichier, id_auteur, likes) VALUES ('untitled1.jpg', '2023-01-02', 1, 'image14', 1, 0);
INSERT INTO images (nom, date, orientation, fichier, id_auteur, likes) VALUES ('untitled2.jpg', '2023-01-12', 1, 'image15', 1, 0);
INSERT INTO images (nom, date, orientation, fichier, id_auteur, likes) VALUES ('autumn in december', '2023-02-18', 1, 'image16', 1, 0);
INSERT INTO images (nom, date, orientation, fichier, id_auteur, likes) VALUES ('zeigefühl zu verlieren', '2023-02-18', 1, 'image17', 1, 0);
INSERT INTO images (nom, date, orientation, fichier, id_auteur, likes) VALUES ('untitled3.jpg', '2023-03-24', 1, 'image18', 1, 0);
INSERT INTO images (nom, date, orientation, fichier, id_auteur, likes) VALUES ('untitled4.jpg', '2023-03-24', 1, 'image19', 1, 0);
INSERT INTO images (nom, date, orientation, fichier, id_auteur, likes) VALUES ('onto memory lane', '2023-04-15', 1, 'image20', 1, 0);
INSERT INTO images (nom, date, orientation, fichier, id_auteur, likes) VALUES ('matsuo basho - ichi', '2023-05-04', 1, 'image21', 1, 0);
INSERT INTO images (nom, date, orientation, fichier, id_auteur, likes) VALUES ('matsuo basho - ni', '2023-05-04', 1, 'image22', 1, 0);
INSERT INTO images (nom, date, orientation, fichier, id_auteur, likes) VALUES ('matsuo basho - san', '2023-05-04', 1, 'image23', 1, 0);
INSERT INTO images (nom, date, orientation, fichier, id_auteur, likes) VALUES ('komorebi', '2023-05-04', 1, 'image24', 1, 0);
INSERT INTO images (nom, date, orientation, fichier, id_auteur, likes) VALUES ('spring', '2023-05-04', 1, 'image25', 1, 0);
INSERT INTO images (nom, date, orientation, fichier, id_auteur, likes) VALUES ('flowers', '2023-05-04', 1, 'image26', 1, 0);